/*
 * Janino - An embedded Java[TM] compiler
 *
 * Copyright (c) 2026 Stefan Zobel. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the
 *       following disclaimer.
 *    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *       following disclaimer in the documentation and/or other materials provided with the distribution.
 *    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
 *       products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.codehaus.commons.compiler.tests;

import java.util.List;

import org.codehaus.commons.compiler.ICompilerFactory;
import org.codehaus.commons.compiler.ISimpleCompiler;
import org.codehaus.commons.compiler.sandbox.BytecodeVerifier;
import org.codehaus.commons.compiler.sandbox.SandboxPolicy;
import org.codehaus.commons.compiler.sandbox.SandboxViolation;
import org.junit.Assert;
import org.junit.Assume;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import util.CommonsCompilerTestSuite;
import util.TestUtil;

/**
 * Tests for the {@link BytecodeVerifier}, applied to the class files generated by the compiler factories.
 */
@RunWith(Parameterized.class) public
class SandboxVerifierTest extends CommonsCompilerTestSuite {

    private static final SandboxPolicy POLICY = SandboxPolicy.builder()
        .include(SandboxPolicy.JAVA_LANG_BASIC)
        .include(SandboxPolicy.COLLECTIONS)
        .build();

    @Parameters(name = "CompilerFactory={0}") public static List<Object[]>
    compilerFactories() throws Exception { return TestUtil.getCompilerFactoriesForParameters(); }

    public
    SandboxVerifierTest(ICompilerFactory compilerFactory) { super(compilerFactory); }

    // -------------------------------------- Code that complies with the policy --------------------------------------

    @Test public void
    testArithmeticAndMath() throws Exception {
        this.assertMethodBodyComplies("return Math.max(3, 7) + Math.abs(-1);");
    }

    @Test public void
    testStringConcatenation() throws Exception {
        this.assertMethodBodyComplies(
            "int i = 1; Object o = new Object(); return \"a\" + i + 'c' + 2.0 + true + o + null + 1L + 1.5f;"
        );
    }

    @Test public void
    testBoxingAndUnboxing() throws Exception {
        this.assertMethodBodyComplies(
            ""
            + "Integer a = 5; int b = a + 1;\n"
            + "Long l = 7L; long m = l;\n"
            + "Character c = 'x'; char d = c;\n"
            + "Boolean t = true; boolean u = t;\n"
            + "Double dd = 1.0; double e = dd;\n"
            + "return Integer.valueOf(b + (int) m + d);\n"
        );
    }

    @Test public void
    testEnhancedFor() throws Exception {
        this.assertMethodBodyComplies(
            ""
            + "java.util.List l = new java.util.ArrayList();\n"
            + "l.add(\"a\");\n"
            + "l.add(\"b\");\n"
            + "String s = \"\";\n"
            + "for (Object o : l) s += o;\n"
            + "int sum = 0;\n"
            + "for (int x : new int[] { 1, 2 }) sum += x;\n"
            + "return s + sum;\n"
        );
    }

    @Test public void
    testSwitchOnString() throws Exception {
        this.assertMethodBodyComplies(
            "String s = \"b\"; switch (s) { case \"a\": return 1; case \"b\": return 2; default: return 3; }"
        );
    }

    @Test public void
    testEnum() throws Exception {
        this.assertCompilationUnitComplies(
            ""
            + "public class Foo {\n"
            + "    public enum Color { RED, GREEN }\n"
            + "    public static Object meth() {\n"
            + "        Color c = Color.valueOf(\"GREEN\");\n"
            + "        switch (c) {\n"
            + "        case RED:   return \"r\";\n"
            + "        case GREEN: return \"g\";\n"
            + "        default:    return Color.values().length + c.name();\n"
            + "        }\n"
            + "    }\n"
            + "}\n"
        );
    }

    @Test public void
    testAssert() throws Exception {
        this.assertMethodBodyComplies("int x = 1; assert x == 1 : \"msg\"; return x;");
    }

    @Test public void
    testTryWithResources() throws Exception {
        this.assertCompilationUnitComplies(
            ""
            + "public class Foo {\n"
            + "    public static class R implements AutoCloseable { public void close() {} }\n"
            + "    public static Object meth() throws Exception { try (R r = new R()) { return \"x\"; } }\n"
            + "}\n"
        );
    }

    @Test public void
    testInnerAndAnonymousClasses() throws Exception {
        this.assertCompilationUnitComplies(
            ""
            + "public class Foo {\n"
            + "    int field = 3;\n"
            + "    class Inner { int get() { return field; } }\n"
            + "    public static Object meth() {\n"
            + "        Runnable r = new Runnable() { public void run() {} };\n"
            + "        r.run();\n"
            + "        java.util.Comparator c = new java.util.Comparator() {\n"
            + "            public int compare(Object a, Object b) { return 0; }\n"
            + "        };\n"
            + "        return new Foo().new Inner().get() + c.compare(\"a\", \"b\");\n"
            + "    }\n"
            + "}\n"
        );
    }

    @Test public void
    testCollections() throws Exception {
        this.assertMethodBodyComplies(
            ""
            + "java.util.Map m = new java.util.HashMap();\n"
            + "m.put(\"k\", \"v\");\n"
            + "java.util.List l = new java.util.ArrayList(java.util.Arrays.asList(new Object[] { \"b\", \"a\" }));\n"
            + "java.util.Collections.reverse(l);\n"
            + "return m.get(\"k\") + l.toString() + l.size() + m.entrySet().size();\n"
        );
    }

    @Test public void
    testExceptions() throws Exception {
        this.assertMethodBodyComplies(
            "try { throw new IllegalStateException(\"x\"); } catch (RuntimeException e) { return e.getMessage(); }"
        );
    }

    /**
     * Verifies that members inherited from a host class through a generated subclass are checked against the
     * declaring host class.
     */
    @Test public void
    testInheritedHostMembers() throws Exception {
        this.assertCompilationUnitComplies(
            ""
            + "public class Foo extends java.util.AbstractList {\n"
            + "    public Object get(int index) { return null; }\n"
            + "    public int size() { return 0; }\n"
            + "    public static Object meth() { return new Foo().subList(0, 0); }\n"
            + "}\n"
        );
        this.assertCompilationUnitViolates(
            ""
            + "public class Foo extends java.util.AbstractList {\n"
            + "    public Object get(int index) { return null; }\n"
            + "    public int size() { return 0; }\n"
            + "    public static Object meth() { return new Foo().getClass().getClassLoader(); }\n"
            + "}\n",
            "Access to java.lang.Class.getClassLoader() is not permitted"
        );
    }

    @Test public void
    testLambdasAndMethodReferences() throws Exception {
        Assume.assumeTrue("JANINO does not support lambdas", this.isJdk);
        this.assertMethodBodyComplies(
            ""
            + "Runnable r = () -> {};\n"
            + "r.run();\n"
            + "java.util.Comparator<String> c = (a, b) -> a.compareTo(b);\n"
            + "java.util.function.Function<String, Integer> f = String::length;\n"
            + "return c.compare(\"a\", \"b\") + \"\" + f;\n"
        );
    }

    @Test public void
    testRecords() throws Exception {
        Assume.assumeTrue("Records require JAVAC 16+", this.isJdk && CommonsCompilerTestSuite.JVM_VERSION >= 16);
        this.assertCompilationUnitComplies(
            ""
            + "public class Foo {\n"
            + "    record P(int x, int y) {}\n"
            + "    public static Object meth() {\n"
            + "        P p = new P(1, 2);\n"
            + "        return p.toString() + p.equals(new P(1, 2)) + p.hashCode() + p.x();\n"
            + "    }\n"
            + "}\n"
        );
    }

    @Test public void
    testPatternSwitch() throws Exception {
        Assume.assumeTrue(
            "Pattern matching for SWITCH requires JAVAC 21+",
            this.isJdk && CommonsCompilerTestSuite.JVM_VERSION >= 21
        );
        this.assertMethodBodyComplies(
            ""
            + "Object o = Integer.valueOf(3);\n"
            + "return switch (o) {\n"
            + "    case Integer i when i > 2 -> \"big\";\n"
            + "    case Integer i            -> \"small\";\n"
            + "    case String s             -> s;\n"
            + "    default                   -> \"other\";\n"
            + "};\n"
        );
    }

    // ---------------------------------------- Code that violates the policy -----------------------------------------

    @Test public void
    testSystemGetProperty() throws Exception {
        this.assertMethodBodyViolates(
            "return System.getProperty(\"foo\");",
            "Access to java.lang.System.getProperty(java.lang.String) is not permitted by the sandbox policy"
        );
    }

    @Test public void
    testSystemOut() throws Exception {
        this.assertMethodBodyViolates("System.out.println(\"x\"); return null;", "java.lang.System.out");
    }

    @Test public void
    testFileDelete() throws Exception {
        this.assertMethodBodyViolates(
            "return new java.io.File(\"path/to/file.txt\").delete();",
            "new java.io.File(java.lang.String)"
        );
    }

    @Test public void
    testSocket() throws Exception {
        this.assertMethodBodyViolates("return new java.net.Socket(\"localhost\", 65000);", "java.net.Socket");
    }

    @Test public void
    testUrlConnection() throws Exception {
        this.assertMethodBodyViolates(
            "return new java.net.URL(\"http://localhost:65000\").openConnection();",
            "java.net.URL"
        );
    }

    @Test public void
    testGetDeclaredField() throws Exception {
        this.assertMethodBodyViolates(
            "return String.class.getDeclaredField(\"CASE_INSENSITIVE_ORDER\");",
            "java.lang.Class.getDeclaredField(java.lang.String)"
        );
    }

    @Test public void
    testClassForName() throws Exception {
        this.assertMethodBodyViolates(
            "return Class.forName(\"java.lang.Runtime\", true, null);",
            "java.lang.Class.forName("
        );
    }

    @Test public void
    testGetClassLoader() throws Exception {
        this.assertMethodBodyViolates(
            "return \"x\".getClass().getClassLoader();",
            "java.lang.Class.getClassLoader()"
        );
    }

    @Test public void
    testIntegerGetInteger() throws Exception {
        this.assertMethodBodyViolates(
            "return Integer.getInteger(\"foo\");",
            "java.lang.Integer.getInteger(java.lang.String)"
        );
    }

    @Test public void
    testThreadSubclass() throws Exception {
        this.assertMethodBodyViolates(
            "new Thread() { public void run() {} }.start(); return null;",
            "Extending java.lang.Thread is not permitted"
        );
    }

    @Test public void
    testParallelStream() throws Exception {
        this.assertMethodBodyViolates(
            "return new java.util.ArrayList().parallelStream();",
            "java.util.Collection.parallelStream()"
        );
    }

    @Test public void
    testServiceLoader() throws Exception {
        this.assertMethodBodyViolates(
            "return java.util.ServiceLoader.load(Runnable.class);",
            "java.util.ServiceLoader.load(java.lang.Class)"
        );
    }

    @Test public void
    testMethodHandlesLookup() throws Exception {
        this.assertMethodBodyViolates(
            "return java.lang.invoke.MethodHandles.lookup();",
            "java.lang.invoke.MethodHandles.lookup()"
        );
    }

    @Test public void
    testMethodReferenceToForbiddenMethod() throws Exception {
        Assume.assumeTrue("JANINO does not support method references", this.isJdk);
        this.assertMethodBodyViolates(
            "java.util.function.Supplier<Runtime> s = Runtime::getRuntime; return s;",
            "java.lang.Runtime.getRuntime()"
        );
    }

    @Test public void
    testNativeMethod() throws Exception {
        this.assertCompilationUnitViolates(
            ""
            + "public class Foo {\n"
            + "    public native void nat();\n"
            + "    public static Object meth() { return null; }\n"
            + "}\n",
            "Native method nat is not permitted"
        );
    }

    @Test public void
    testForbiddenSuperclass() throws Exception {
        this.assertCompilationUnitViolates(
            ""
            + "public class Foo extends java.util.ArrayList {\n"
            + "    public static Object meth() { return null; }\n"
            + "}\n",
            "Extending java.util.ArrayList is not permitted"
        );
    }

    @Test public void
    testEmptyPolicy() throws Exception {
        List<SandboxViolation> violations = this.verify(
            "public class Foo { public static Object meth() { return \"x\".length(); } }",
            SandboxPolicy.builder().build()
        );
        Assert.assertEquals(violations.toString(), 1, violations.size());
        Assert.assertEquals("Foo", violations.get(0).getClassName());
        Assert.assertEquals(
            "Access to java.lang.String.length() is not permitted by the sandbox policy",
            violations.get(0).getMessage()
        );
    }

    // ================================================ HELPERS ================================================

    private void
    assertMethodBodyComplies(String methodBody) throws Exception {
        this.assertCompilationUnitComplies(SandboxVerifierTest.compilationUnit(methodBody));
    }

    private void
    assertMethodBodyViolates(String methodBody, String expectedMessagePart) throws Exception {
        this.assertCompilationUnitViolates(SandboxVerifierTest.compilationUnit(methodBody), expectedMessagePart);
    }

    private void
    assertCompilationUnitComplies(String compilationUnit) throws Exception {
        List<SandboxViolation> violations = this.verify(compilationUnit, SandboxVerifierTest.POLICY);
        Assert.assertTrue(violations.toString(), violations.isEmpty());
    }

    private void
    assertCompilationUnitViolates(String compilationUnit, String expectedMessagePart) throws Exception {
        List<SandboxViolation> violations = this.verify(compilationUnit, SandboxVerifierTest.POLICY);
        for (SandboxViolation v : violations) {
            if (v.getMessage().contains(expectedMessagePart)) return;
        }
        Assert.fail("Expected a violation containing \"" + expectedMessagePart + "\", but got " + violations);
    }

    private List<SandboxViolation>
    verify(String compilationUnit, SandboxPolicy policy) throws Exception {
        ISimpleCompiler sc = this.compilerFactory.newSimpleCompiler();
        sc.cook(compilationUnit);
        return new BytecodeVerifier(policy).verify(sc.getBytecodes(), SandboxVerifierTest.class.getClassLoader());
    }

    private static String
    compilationUnit(String methodBody) {
        return "public class Foo { public static Object meth() throws Exception {\n" + methodBody + "\n} }\n";
    }
}
